# Copyright (c) 2025 Andrea Pozzetti
# SPDX-License-Identifier: MIT
"""Generate mesh geometry from skeleton joint positions for visualization."""

import numpy as np
import struct


def write_stl(filepath, vertices, faces):
    """
    Write mesh to binary STL file.

    Args:
        filepath: Output file path
        vertices: [N, 3] array of vertex positions
        faces: [M, 3] array of face indices (triangles)
    """
    vertices = np.asarray(vertices, dtype=np.float32)
    faces = np.asarray(faces, dtype=np.int32)

    if len(vertices) == 0 or len(faces) == 0:
        # Write empty STL
        with open(filepath, 'wb') as f:
            f.write(b'\x00' * 80)  # Header
            f.write(struct.pack('<I', 0))  # 0 triangles
        return

    with open(filepath, 'wb') as f:
        # 80-byte header
        header = f"STL generated by SAM3DBody debug".encode('ascii')
        header = header[:80].ljust(80, b'\x00')
        f.write(header)

        # Number of triangles
        f.write(struct.pack('<I', len(faces)))

        for face in faces:
            v0 = vertices[face[0]]
            v1 = vertices[face[1]]
            v2 = vertices[face[2]]

            # Compute face normal
            edge1 = v1 - v0
            edge2 = v2 - v0
            normal = np.cross(edge1, edge2)
            norm_len = np.linalg.norm(normal)
            if norm_len > 1e-8:
                normal = normal / norm_len
            else:
                normal = np.array([0.0, 0.0, 1.0], dtype=np.float32)

            # Write: normal (3 floats), v0, v1, v2 (9 floats), attribute (2 bytes)
            f.write(struct.pack('<fff', float(normal[0]), float(normal[1]), float(normal[2])))
            f.write(struct.pack('<fff', float(v0[0]), float(v0[1]), float(v0[2])))
            f.write(struct.pack('<fff', float(v1[0]), float(v1[1]), float(v1[2])))
            f.write(struct.pack('<fff', float(v2[0]), float(v2[1]), float(v2[2])))
            f.write(struct.pack('<H', 0))  # Attribute byte count


def create_skeleton_mesh(joint_positions, joint_parents, bone_radius=0.01, joint_radius=0.015):
    """
    Create mesh geometry visualizing a skeleton.

    Args:
        joint_positions: [N, 3] array of joint positions
        joint_parents: [N] array of parent indices (-1 for root)
        bone_radius: Radius of bone cylinders
        joint_radius: Radius of joint spheres

    Returns:
        dict with 'vertices' and 'faces' arrays
    """
    if joint_positions is None:
        return {"vertices": np.zeros((0, 3)), "faces": np.zeros((0, 3), dtype=int)}

    joint_positions = np.asarray(joint_positions)
    joint_parents = np.asarray(joint_parents)

    all_verts = []
    all_faces = []
    vert_offset = 0

    # Add joint spheres (low-poly icosphere)
    for i, pos in enumerate(joint_positions):
        verts, faces = _create_icosphere(pos, joint_radius)
        if verts is not None and len(verts) > 0:
            all_verts.append(verts)
            all_faces.append(faces + vert_offset)
            vert_offset += len(verts)

    # Add bone cylinders
    for i, parent_idx in enumerate(joint_parents):
        if parent_idx >= 0 and parent_idx < len(joint_positions):
            start = joint_positions[parent_idx]
            end = joint_positions[i]
            verts, faces = _create_cylinder(start, end, bone_radius)
            if verts is not None and len(verts) > 0:
                all_verts.append(verts)
                all_faces.append(faces + vert_offset)
                vert_offset += len(verts)

    if all_verts:
        vertices = np.vstack(all_verts)
        faces = np.vstack(all_faces)
    else:
        vertices = np.zeros((0, 3))
        faces = np.zeros((0, 3), dtype=int)

    return {
        "vertices": vertices,
        "faces": faces,
    }


def _create_cylinder(start, end, radius, segments=8):
    """Create cylinder mesh between two points."""
    start = np.asarray(start, dtype=np.float64)
    end = np.asarray(end, dtype=np.float64)

    direction = end - start
    length = np.linalg.norm(direction)
    if length < 1e-6:
        return None, None

    direction_norm = direction / length

    # Find perpendicular vectors
    if abs(direction_norm[1]) < 0.99:
        perp1 = np.cross(direction_norm, np.array([0.0, 1.0, 0.0]))
    else:
        perp1 = np.cross(direction_norm, np.array([1.0, 0.0, 0.0]))
    perp1 = perp1 / np.linalg.norm(perp1)
    perp2 = np.cross(direction_norm, perp1)

    # Generate circle vertices
    angles = np.linspace(0, 2*np.pi, segments, endpoint=False)
    vertices = []
    for angle in angles:
        offset = radius * (np.cos(angle) * perp1 + np.sin(angle) * perp2)
        vertices.append(start + offset)
    for angle in angles:
        offset = radius * (np.cos(angle) * perp1 + np.sin(angle) * perp2)
        vertices.append(end + offset)

    # Generate faces (triangles for the side walls)
    faces = []
    for i in range(segments):
        next_i = (i + 1) % segments
        # Two triangles per quad
        faces.append([i, next_i, next_i + segments])
        faces.append([i, next_i + segments, i + segments])

    # Add caps
    # Bottom cap center
    vertices.append(start)
    bottom_center_idx = len(vertices) - 1
    # Top cap center
    vertices.append(end)
    top_center_idx = len(vertices) - 1

    # Bottom cap triangles
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([bottom_center_idx, next_i, i])

    # Top cap triangles
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([top_center_idx, i + segments, next_i + segments])

    return np.array(vertices), np.array(faces, dtype=int)


def _create_icosphere(center, radius, subdivisions=0):
    """Create low-poly sphere at position (icosahedron base)."""
    center = np.asarray(center, dtype=np.float64)

    # Golden ratio icosahedron base
    t = (1.0 + np.sqrt(5.0)) / 2.0
    vertices = np.array([
        [-1, t, 0], [1, t, 0], [-1, -t, 0], [1, -t, 0],
        [0, -1, t], [0, 1, t], [0, -1, -t], [0, 1, -t],
        [t, 0, -1], [t, 0, 1], [-t, 0, -1], [-t, 0, 1]
    ], dtype=np.float64)

    # Normalize to unit sphere, then scale by radius and translate
    for i in range(len(vertices)):
        vertices[i] = vertices[i] / np.linalg.norm(vertices[i]) * radius + center

    faces = np.array([
        [0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11],
        [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8],
        [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9],
        [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1]
    ], dtype=int)

    return vertices, faces


def create_axes_mesh(origin, scale=0.1, thickness=0.005):
    """
    Create coordinate axes visualization at a given origin.

    Args:
        origin: [3] array, center point of the axes
        scale: Length of each axis
        thickness: Radius of axis cylinders

    Returns:
        dict with 'vertices' and 'faces' arrays
    """
    origin = np.asarray(origin, dtype=np.float64)

    all_verts = []
    all_faces = []
    vert_offset = 0

    # X axis (red direction)
    end_x = origin + np.array([scale, 0, 0])
    verts, faces = _create_cylinder(origin, end_x, thickness)
    if verts is not None:
        all_verts.append(verts)
        all_faces.append(faces + vert_offset)
        vert_offset += len(verts)

    # Y axis (green direction)
    end_y = origin + np.array([0, scale, 0])
    verts, faces = _create_cylinder(origin, end_y, thickness)
    if verts is not None:
        all_verts.append(verts)
        all_faces.append(faces + vert_offset)
        vert_offset += len(verts)

    # Z axis (blue direction)
    end_z = origin + np.array([0, 0, scale])
    verts, faces = _create_cylinder(origin, end_z, thickness)
    if verts is not None:
        all_verts.append(verts)
        all_faces.append(faces + vert_offset)
        vert_offset += len(verts)

    if all_verts:
        return {
            "vertices": np.vstack(all_verts),
            "faces": np.vstack(all_faces),
        }
    return {"vertices": np.zeros((0, 3)), "faces": np.zeros((0, 3), dtype=int)}
